version: "3.3"

services:
  web:
    build: .
    volumes:
      - /usr/share/nginx/images.pc28:/usr/share/nginx/html
      - /etc/nginx/conf.d/images_docker.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/nginx_docker:/etc/nginx/nginx.conf
    ports:
      - 91:80 #maquina/docker
